name: Python Tests

on: [ push, pull_request ]

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup_python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pythin -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest ./tests